WITH A AS (
    SELECT 
        ID, 
        SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_QUARTILE
    FROM 
        ECOLI_DATA
)
SELECT 
    ID,
    CASE
        WHEN RANK_QUARTILE = 1 THEN 'CRITICAL'
        WHEN RANK_QUARTILE = 2 THEN 'HIGH'
        WHEN RANK_QUARTILE = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM 
    A
ORDER BY 
    ID;