SELECT t1.ID ID, t1.GENOTYPE, t2.GENOTYPE PARENT_GENOTYPE
FROM (
    SELECT ID, PARENT_ID, GENOTYPE
    FROM ECOLI_DATA
) AS t1
JOIN (
    SELECT ID, GENOTYPE
    FROM ECOLI_DATA
) AS t2
ON t1.PARENT_ID = t2.ID AND (t1.GENOTYPE & t2.GENOTYPE) = t2.GENOTYPE
ORDER BY 1;